### ISSUE TITLE
NMS has error with pytorch 2.0

### ISSUE THREAD

**Issue by tsbiosky** [SizheAn/mRI#10]
import nms_1d_cpu
ImportError: /home/hjx20/.local/lib/python3.8/site-packages/nms_1d_cpu-0.0.0-py3.8-linux-x86_64.egg/nms_1d_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorEll

I build the c++ code of NMS successfully,  but when I ran training I got this error 
is the pytorch version must be pytorch==1.11?

**Comment by SizheAn** [comment]
Sorry we haven't tested the code in pytorch 2.0. Please use the advised version of libraries :)
