### ISSUE TITLE
How to  get the ground truth of human skeletal points?

### ISSUE THREAD

**Issue by weizixiu** [SizheAn/mRI#4]
Hi, Mr. An. I don't know how to get the ground truth of human skeletal points.
It seems like that i should read the XXX.cpl files in pose_labels , but i don't know how to do that exzactly. Because it is a kind of  control panel files, and it is uselessly to double click them.
So, could you help me for that question? Thank you!

**Comment by SizheAn** [comment]
Hi there,

Thanks a lot for interest in our work. You can treat it as a pickle file and do the following do access it:

```
import pickle
file = pickle.load(open('.../file_path/XXX.cpl', 'rb'))
```
Let me know if you have further questions!

**Comment by weizixiu** [comment]
> 
Hi,Mr. An.
I have try the above codes,
```
import pickle
file = pickle.load(open('./aligned_data/pose_labels/subject2.cpl', 'r'))
```
But there are some error as follow:
**UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence**
So, i try to use the argument 'encoding=utf-8', but it still don't work.
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte**
Is there something wrong? Wish your reply!

**Comment by SizheAn** [comment]
> 

Try change 'r' to 'rb'

**Comment by SizheAn** [comment]
> > 
> 
> Hi,Mr. An. I have try the above codes,
> 
> ```
> import pickle
> file = pickle.load(open('./aligned_data/pose_labels/subject2.cpl', 'r'))
> ```
> 
> But there are some error as follow: **UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence** So, i try to use the argument 'encoding=utf-8', but it still don't work. **UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte** Is there something wrong? Wish your reply!

Try change 'r' to 'rb'?

**Comment by weizixiu** [comment]
> > > 
> > 
> > 
> > Hi,Mr. An. I have try the above codes,
> > ```
> > import pickle
> > file = pickle.load(open('./aligned_data/pose_labels/subject2.cpl', 'r'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But there are some error as follow: **UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence** So, i try to use the argument 'encoding=utf-8', but it still don't work. **UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte** Is there something wrong? Wish your reply!
> 
> Try change 'r' to 'rb'?



> 
Ohh!!!
It works! Thank you!

**Comment by weizixiu** [comment]
> > > 
> > 
> > 
> > Hi,Mr. An. I have try the above codes,
> > ```
> > import pickle
> > file = pickle.load(open('./aligned_data/pose_labels/subject2.cpl', 'r'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But there are some error as follow: **UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 0: illegal multibyte sequence** So, i try to use the argument 'encoding=utf-8', but it still don't work. **UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte** Is there something wrong? Wish your reply!
> 
> Try change 'r' to 'rb'?



> 
Ohh!!!
It works! Thank you!
