### ISSUE TITLE
Point cloud from mmwave radar

### ISSUE THREAD

**Issue by duyddwcs** [SizheAn/mRI#5]
How can I generate point cloud data from raw IQ data collected from DCA1000EVM? Many thanks in advance.

**Comment by SizheAn** [comment]
Hi there, while we do not use DCA1000EVM board for the data collection purpose (we use zone occupancy matlab project from TI), I believe it is doable using those equations in the paper.

**Comment by duyddwcs** [comment]
https://www.ti.com/lit/ug/tiduea7/tiduea7.pdf?ts=1677484268326&ref_url=https%253A%252F%252Fwww.google.com%252F

Is this what you're refer to?

**Comment by SizheAn** [comment]
> https://www.ti.com/lit/ug/tiduea7/tiduea7.pdf?ts=1677484268326&ref_url=https%253A%252F%252Fwww.google.com%252F
> 
> Is this what you're refer to?

Yes.
