### ISSUE TITLE
How to open the .cpl files in the aligned data folder?

### ISSUE THREAD

**Issue by Carbord** [SizheAn/mRI#6]
Hello! After unzipping the dataset, I found that the data files were save as .cpl files in the folder 'pose labels' under the 'aligned data' folder. I would like to ask how to extract the data from those files, or whether it is possible to transform them into other formats like .npy quickly. Thank a lot!

**Comment by SizheAn** [comment]
Check this issue: https://github.com/SizheAn/mRI/issues/4
After reading .cpl successfully, it is essentially just dict with many numpy array
